### ISSUE TITLE
ResNet-34...

### ISSUE THREAD

**Issue by amiltonwong** [ageron/handson-ml#18]
Hi, @ageron ,

According to the notes mentioned in book,
![notes](https://cloud.githubusercontent.com/assets/2517000/25618809/09067da8-2f7b-11e7-99f5-36639b06b63d.jpg) 
the ResNet-34 model is to be implemented. However, I cannot find it in  `13_convolutional_neural_networks.ipynb`. Could you help to upload it?

THX~

**Comment by ageron** [comment]
Hi @amiltonwong,

Yes, I'm a bit late with the exercise solutions, I apologize.  I'm currently working on them: I plan to upload solutions chapter per chapter, every few days.  I recently pushed exercise solutions for chapter 2, and I'm working on solutions for chapter 3.  That said, if you are blocked in chapter 13, I can work on that chapter next.

**Comment by amiltonwong** [comment]
Thanks @ageron for your quick reply.
Yes, currently I have a project which needs ResNet and I'm looking for ResNet implementation. So it would be  highly appreciated if you will release its implementation (ch13 exercise) next.

Thanks!

**Comment by ageron** [comment]
Working on it! In the meantime you can check out the implementations in the TensorFlow zoo:
https://github.com/tensorflow/models/blob/6c9d2eba3f6fb766eb62b752efb670fed00dadf5/slim/nets/resnet_v1.py

**Comment by amiltonwong** [comment]
Thanks a lot :)

**Comment by ageron** [comment]
Hi @amiltonwong ,

If you are interested, I pushed the solutions to the Chapter 13 exercises.  In doing so I realized that the exercises actually don't cover ResNet-34: the sentence _"we will build ResNet-34..."_ reflected my initial intention, but when preparing the exercises, I settled for building simpler CNNs and forgot to remove that sentence. I sincerely apologize.  I removed that sentence from the book.

I can still add a ResNet-34 implementation at the end of the notebook, but before I spend time working on that, I was wondering if it was really worth it, since the TensorFlow zoo already has a pretty straightforward implementation: what do you think?

Thanks for your feedback,
Aurélien

**Comment by amiltonwong** [comment]
Hi, @ageron ,

Thanks a lot for your effort. I'll check it.
For ResNet-34 implementation, frankly speaking, I'm quite eager for it because still can't find a complete tutorial/blog/notebook about the ResNet implementation using pure tf / tf-slim. For quick solution, I try it in Keras and it looks quite straight-ward and concise.

**Comment by ageron** [comment]
Fair enough, I promised it, I'll do it!  However, I'm not sure exactly when I'll have time, but I'll keep you posted. :)

**Comment by amiltonwong** [comment]
Thank you so much :)

**Comment by mercuro1** [comment]
Hi @ageron:
      I am a novice in mechanine learning. Your book helps me a lot and the ResNet is too hard for me, could you please loadup ResNet-34 implementation?
